# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dan <dan@student.42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/02 10:40:29 by dsylvain          #+#    #+#              #
#    Updated: 2024/01/17 16:18:22 by dan              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libftprintf.a

CC = cc

CFLAGS = -Wall -Wextra -Werror -Wno-unused-result

SRC =	source_files/ft_printf.c \
		source_files/ft_printf_utils.c \
		source_files/print_functions.c \
		source_files/print_functions_2.c \
		source_files/specifier_handler_funcs.c \
		source_files/specifier_handler_funcs_2.c

OBJ = $(SRC:.c=.o)

OBJ_BONUS = $(SRC_BONUS:_bonus.c=_bonus.o)

all: $(NAME)

$(NAME): $(OBJ)
	@ar rcs	$(NAME)	$(OBJ)
	@printf "%-80s\033[0;32mcompiled\033[0m\n" $(NAME)

%.o: %.c
	@{ $(CC) $(CFLAGS) -I$(LIBFT_DIR) -I/usr/include -O3 -c $< -o $@; } 2>&1 || \
		(echo "\033[0;31mCompilation of $< failed\033[0m"; exit 1)
clean:
	@rm	-f	$(OBJ) $(OBJ_BONUS)

fclean: clean
	@rm	-f	$(NAME) 

re:	fclean	all
